version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build-and-push-image:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run: ./gradlew :fineract-provider:jibDockerBuild -x test 

workflows:
  staging-build-image:
    jobs:
      - build-and-push-image
