version: 2.1

orbs:
  ci-cd: djamoapp/ci-cd@0.1.2

workflows:
  staging-build-image:
    jobs:
      - ci-cd/build-and-push-image:
          ecr-repo: fineract
          app-env: staging
          context: [aws-registry-creds, slack-secrets]
          channel: C05CBV9L9G8
          filters:
            branches:
              only:
                - 1.7.3
